import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/header/Header";
import { SanityLive } from "@/sanity/lib/live";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className="flex min-h-screen">
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-col w-full">
              <SidebarInset>
                <Header />
              </SidebarInset>
              <main className="flex-1">{children}</main>
            </div>
          </SidebarProvider>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
